### ISSUE TITLE
Enable to block all ports

### ISSUE THREAD

**Issue by arthur-leclerc** [Twingate/kubernetes-operator#192]
**What happened?**

I'm unable to block all ports on a `TwingateResource` when using:

```yaml
  protocols:
    udp:
      policy: RESTRICTED
      ports: []
```

**Did you expect to see something different?**

I'm pretty sure that's the way to do it though. When I look at the call from the website, the GraphQL call looks like this:

<img width="214" alt="Capture d’écran 2024-03-12 à 00 00 36" src="https://github.com/Twingate/kubernetes-operator/assets/43139375/6d9c537c-1ad2-4bbb-ac68-79f042c90254">

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Twingate Kubernetes Operator version:

    `twingate/kubernetes-operator:0.6.1`
    

* Kubernetes version information:

```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3
```

* Kubernetes cluster kind:

    AWS EKS

* Manifests:

```yaml
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: foo
spec:
  name: Foo
  address: foo.default.cluster.local
  protocols:
    allowIcmp: true
    tcp:
      policy: RESTRICTED
      ports:
        - end: 8080
          start: 8080
    udp:
      policy: RESTRICTED
      ports: []
```

* Twingate Kubernetes Operator Logs:

```
Invalid value: "object": Can't specify port ranges for ALLOW_ALL policy, and must specify port ranges for RESTRICTED policy
```

**Anything else we need to know?**:
