### ISSUE TITLE
Ability to import existing Twingate resources?

### ISSUE THREAD

**Issue by zvickery** [Twingate/kubernetes-operator#245]
**What is missing?**
We have quite a few resources managed by Terraform in Twingate.  While this is fine, I think managing them with the operator would be easier and more developer-friendly going forward.  Will there be a way to migrate existing resources to the CRD/operator in the future?  AFAICT this does not exist currently.

**Why do we need it?**
This is definitely not a need, just a nice-to-have for existing customers.

**Environment**

* Twingate Kubernetes Operator version:

    `docker.io/twingate/kubernetes-operator@sha256:716b07e83b6acaaea13827cb0ab66ddee231c27133ccf1cc438793a478a08929`

**Anything else we need to know?**:
Nope.  The operator looks really promising!

**Comment by ekampf** [comment]
When you apply a `TwingateResource` yaml, once its synced to Twingate, the operator adds an `id` value to it (`spec.id`).
If you create your resources with the `id` value pre-populated the operator will not try to create a new resource and will only reconcile differences should ones occure

**Comment by zvickery** [comment]
I attemped to do this sort of thing.  Here is my resource:
```
---
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: test-resource
  namespace: myns
spec:
  name: myresource
  address: myaddress
  isBrowserShortcutEnabled: True
  id: EXISTING_ID
  protocols:
    tcp:
      policy: RESTRICTED
      ports:
      - start: 443
        end: 443
    udp:
      policy: RESTRICTED
      ports:
      - start: 443
        end: 443
    allowIcmp: false
```
However it ends up creating a duplicate resource.  In the resource events I see:
```
  Normal  Logging  32s   kopf  Got a create request: {'address': 'myaddress', 'id': 'EXISTING_ID', 'isBrowserShortcutEnabled': True, 'isVisible': True, 'name': 'myresource', 'protocols': {'allowIcmp': False, 'tcp': {'policy': 'RESTRICTED', 'ports': [{'end': 443, 'start': 443}]}, 'udp': {'policy': 'RESTRICTED', 'ports': [{'end': 443, 'start': 443}]}}}
  Normal  Logging  31s   kopf  Creation is processed: 1 succeeded; 0 failed.
  Normal  Logging  31s   kopf  Got resource id='NEW_ID' name='myresource' created_at=datetime.datetime(2024, 4, 10, 23, 0, 52, 780102, tzinfo=TzInfo(UTC)) updated_at=datetime.datetime(2024, 4, 10, 23, 0, 53, 559545, tzinfo=TzInfo(UTC)) address=ResourceAddress(type='DNS', value='myaddress') is_visible=True is_browser_shortcut_enabled=True remote_network=ResourceRemoteNetwork(id='NW_ID') alias=None security_policy=None protocols=ResourceProtocols(allow_icmp=False, tcp=ResourceProtocol(policy=<ProtocolPolicy.RESTRICTED: 'RESTRICTED'>, ports=[ProtocoRange(start=443, end=443)]), udp=ResourceProtocol(policy=<ProtocolPolicy.RESTRICTED: 'RESTRICTED'>, ports=[ProtocoRange(start=443, end=443)]))
  Normal  Logging  31s   kopf  Updating resource NEW_ID
  Normal  Logging  31s   kopf  Handler 'twingate_resource_update/spec' succeeded.
  Normal  Success  31s   kopf  Created on Twingate as NEW_ID
  Normal  Logging  31s   kopf  Updating is processed: 1 succeeded; 0 failed.
```
It doesn't seem like it is trying to attach to the existing resource.  Does my example seem like it should?
