### ISSUE TITLE
Operator created connector should use metadata.name as connector name in Twingate Web Control Panel

### ISSUE THREAD

**Issue by AlexisDaciuk** [Twingate/kubernetes-operator#290]
**What is missing?**

Naming consistency, now the operator created connector uses a randomly generated name instead of the name that is defined in the Kubernetes resources metadata field

**Why do we need it?**

Easier identification when looking at the remote network from the Twingate Web Control Panel

**Environment**

* Twingate Kubernetes Operator version:

acf0a72

**Anything else we need to know?**:

**Comment by ekampf** [comment]
`TwingateConnector` has a [`spec.name`](https://github.com/Twingate/kubernetes-operator/wiki/API-Reference#twingateconnectorspec) attribute. 
Is that what you're looking for?

Example:
```
apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: my-connector-auto-updating-image
spec:
  name: "My Auto-Updating Connector"
  imagePolicy:
    schedule: "0 0 * * *"
    version: "^1.0.0"
```
