### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by jtschelling** [Twingate/kubernetes-operator#337]
**What is missing?**

Some sort of way to attach a Twingate resource to a resource created by an ingress.

**Why do we need it?**

We use the AWS LB Controller project and spin up a ton of LBs with it. It'd be great to be able to put some sort of annotation or something on the ingress object to get that in Twingate without have to jump between k8s/terraform (where we're creating other Twingate resources).

**Environment**

* Twingate Kubernetes Operator version:

    N/A

**Anything else we need to know?**:

Thinking something like this would be my preferred UX:

```yaml
apiVersion: networking.k8s.io/v1                                                                                                                                                              
kind: Ingress                                                                                                                                                                                 
metadata:                                                                                                                                                                                     
  annotations:                                                                                                                                                                                
    alb.ingress.kubernetes.io/group.name: my-alb-group                                                                                                                            
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80, "HTTPS":443}]'                                                                                                                      
    alb.ingress.kubernetes.io/scheme: internal                                                                                                                                                
    alb.ingress.kubernetes.io/ssl-redirect: "443"                                                                                                                                             
    alb.ingress.kubernetes.io/target-type: ip
    ingress.twingate.com/resource: "true"
    ingress.twingate.com/set-resource-alias: "true"
  name: my-ingress                                                                                                                                                                           
  namespace: my-namespace                                                                                                                                              
spec:                                                                                                                                                                                         
  ingressClassName: alb                                                                                                                                                                       
  rules:                                                                                                                                                                                      
  - host: my-service.my-environment.my-domain.com                                                                                                                                             
    http:                                                                                                                                                                                     
      paths:                                                                                                                                                                                  
      - backend:                                                                                                                                                                              
          service:                                                                                                                                                                            
            name: my-service                                                                                                                                                                 
            port:                                                                                                                                                                             
              number: 8080                                                                                                                                                                    
        path: /*                                                                                                                                                                                                                                                                                                                                   
```

which would get a status block from the aws lb controller like:

```yaml
status:                                                                                                                                                                                       
  loadBalancer:                                                                                                                                                                               
    ingress:                                                                                                                                                                                  
    - hostname: internal-myalbgroup-123456789-123456789.us-east-1.elb.amazonaws.com                                                                                              
```

then you'd get a Twingate resource with address `internal-myalbgroup-123456789-123456789.us-east-1.elb.amazonaws.com` and alias `my-service.my-environment.my-domain.com`

i'm honestly not even sure you could do this. The ingress resources outputs a `loadBalancer.ingress.hostname` field you could use as the Twingate resource address that I think all ingress controllers should output? maybe getting the `spec.rules.host` fields works?
