### ISSUE TITLE
feat: Inject Headless client sidecar to annotated deployments\statefulsets

### ISSUE THREAD

**Issue by ekampf** [Twingate/kubernetes-operator#533]
**What is missing?**
There's a use case for using a Twingate headless client sidecar to allow processes to access secure resources

**Why do we need it?**
Example use case: Helm\Grafana accessing datasources on clusters in remote VPCs

**Anything else we need to know?**:

There's a sample on how to get sidecar working at https://github.com/Twingate-Labs/tg-client-k8s-sidecar
Basically the idea is:
- Define a `deployment` / `statefulset` with a volume that maps to a Service Account secret token
- Add an annotation: `sa.twingate.com/key: <the volume name>`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: main-container
          image: ubuntu:latest
          command: ... do whatever ...
      volumes:
        - name: service-key
          secret:
            secretName: service-key
```

Operator would then inject sidecar:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: main-container
          image: ubuntu:latest
          command: ... do whatever ...
        - name: sidecar-container
          image: ubuntu:latest
          securityContext:
            privileged: true
          command: ["/bin/sh","-c"]
          args:
            - apt-get update;
              apt-get install curl -y;
              curl https://binaries.twingate.com/client/linux/install.sh | bash;
              sudo twingate setup --headless /etc/twingate-service-key/key.base64;
              sudo twingate start;
              sleep infinity;
          volumeMounts:
            - mountPath: "/etc/twingate-service-key/"
              name: service-key
              readOnly: true
      volumes:
        - name: service-key
          secret:
            secretName: service-key
```

**Comment by arollyson** [comment]
This injection pattern would be very nice.

For what it's worth, you can grant the sidecar with a lower set of permissions without having to use `privileged: true`. We're actively using this pattern in several places.

You only need to add `NET_ADMIN` and to mount `/dev/net/tun`:
```yaml
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - mountPath: "/etc/twingate-service-key/"
          name: service-key
          readOnly: true
        - mountPath: "/dev/net/tun"
          name: tun-device
```
and the volume
```yaml
  volumes:
    - name: service-key
      secret:
        secretName: twingate-service-key
    - name: tun-device
      hostPath:
        path: /dev/net/tun
```

`privileged: true` adds all kinds of unnecessary capabilities, creating security issues.

**Comment by legal90** [comment]
Thank you for you input @arollyson !  
I'm currently trying to solve a very similar issue.
Could you please share mare details of the container spec in your case? 
I wonder how you setup and start the twingate client inside that sidecar. Cheers!

**Comment by arollyson** [comment]
The deployment manifest linked in the OP works just fine with those modifications: https://github.com/Twingate-Labs/tg-client-k8s-sidecar.

The one other modification I personally make is doing an explicit install instead of curl>bash:
```yaml
      args:
        - apt-get update;
          apt-get install -yq ca-certificates;
          echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" > /etc/apt/sources.list.d/twingate.list;
          apt-get update -yq;
          apt-get install -yq twingate;
```

(with an aside plug for eventually getting some published GPG keys and signed packages @ekampf 👀)

**Comment by arollyson** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twingate-example-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twingate-example-sidecar
  template:
    metadata:
      labels:
        app: twingate-example-sidecar
    spec:
      containers:
        - name: main-container
          image: public.ecr.aws/ubuntu/ubuntu:24.04_stable
          command: [ "/bin/sh","-c" ]
          args:
            - apt-get update;
              sleep infinity;
        - name: sidecar-container
          image: public.ecr.aws/ubuntu/ubuntu:24.04_stable
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/sh","-c"]
          args:
            - apt-get update;
              apt-get install -yq ca-certificates;
              echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" > /etc/apt/sources.list.d/twingate.list;
              apt-get update -yq;
              apt-get install -yq twingate;
              cat /etc/twingate-service-key/key.base64 | base64 --decode | twingate setup --headless=-;
              twingate start;
              sleep infinity;
          volumeMounts:
            - mountPath: /etc/twingate-service-key/
              name: service-key
              readOnly: true
            - mountPath: /dev/net/tun
              name: tun-device
      volumes:
        - name: service-key
          secret:
            secretName: twingate-service-key
        - name: tun-device
          hostPath:
            path: /dev/net/tun
```

**Comment by romankor** [comment]
I am running the sidecar the same way , and still getting permission errors 

```
│ Reading package lists...                                                                                                │
│ E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)                              │
│ E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)                                  │
│ E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?                                │
│ /bin/sh: 1: cannot create /etc/apt/sources.list.d/twingate.list: Permission denied                                      │
│ Reading package lists...                                                                                                │
│ E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)                              │
│ E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)                                  │
│ E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?                                │
│ /bin/sh: 1: twingate: not found                                                                                         │
│ /bin/sh: 1: twingate: not found
```

I am running it as a sidecar of grafana to access datasources that are in other cloud providers. 

Grafana by default runs with the following security context

```
  securityContext:
    fsGroup: 472
    runAsGroup: 472
    runAsNonRoot: true
    runAsUser: 472
```

and running the sidecar as root is not really an option , since it would violate pods non root policy 

Is my error related to that, that the grafana doesn't run in root ?

**Comment by legal90** [comment]
With all these complications, I'd like to reach out to Twingate folks:
- Is that OK to use a pre-built container image with Twingate client installed? So, we only will have to do `[sudo] twingate stup` and `twingate start` when container starts. What are possible downsides of this?
- Does Twingate plan to maintain an official container image for Twingate Client? I see that there is some initiative in the community: https://github.com/Docker-Collection/docker-twingate-headless

**Comment by ekampf** [comment]
@legal90 we don't publish a client container at the moment, but we want to.
I think the solution above of running an ubuntu container and doing the installation on start is not optimal - now that we see that there's traction for this we will work on releasing a pre-built container. No ETA yet but I hope soon...

**Comment by ekampf** [comment]
I didnt know https://github.com/Docker-Collection/docker-twingate-headless thats pretty cool!

**Comment by legal90** [comment]
Thank you, @ekampf!  It would be really useful to have such container image! 🙏 
--------------
Back to the original topic, so far the most optimal and secure setup is with an image `ghcr.io/docker-collection/twingate_headless`. It looks like this:

```yaml
  spec:
    initContainers:
      - name: twingate-headless
        image: ghcr.io/docker-collection/twingate_headless:latest
        env:
          - name: SERVICE_KEY
            valueFrom:
              secretKeyRef:
                name: twingate-service-key
                key: twingate-service-key
        volumeMounts:
          - mountPath: "/dev/net/tun"
            name: host-tun-device
        securityContext:
          runAsNonRoot: false # Twingate client needs to run as root
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
            add:
              - NET_ADMIN # needed for Twingate to open a tunnel
              - SETUID # needed for `twingate start`
              - SETGID # needed for `twingate start`

        # This makes it to run as a "native sidecar" - it starts before the main container,
        # and unlike classic `initContainers` remain running during the entire life of the Pod.
        # https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
        restartPolicy: Always

    containers:
      - name: my_workload
        image: <my_workload_image>
        # <...skipped...>
        securityContext:
          runAsUser: 1001
          runAsGroup: 123
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: [ALL]

    volumes:
      - name: host-tun-device
        hostPath:
          path: /dev/net/tun
      - name: twingate-service-key
        secret:
          secretName: twingate-service-key

    securityContext:
      fsGroup: 123
```
