### ISSUE TITLE
fix: K8s Service annotations are not removed from Twingate Resource

### ISSUE THREAD

**Issue by clement0010** [Twingate/kubernetes-operator#607]
**What happened?**
When an existing annotation is removed from k8s Service, the corresponding annotation is still kept on `TwingateResource` CRD. The current behavior seems to support adding or updating the annotations only.

**Did you expect to see something different?**
Remove the corresponding annotation on `TwingateResource` CRD when it is removed from k8s `Service`.

**How to reproduce it (as minimally and precisely as possible)**:
Consider the following `service.yaml` file:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    resource.twingate.com: "true"
    resource.twingate.com/alias: "myapp.internal"
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      name: first
    - protocol: UDP
      port: 22
      targetPort: 9376
      name: second
```

1. Create a k8s Service: `kubectl apply -f service.yaml`
2. Verify annotation on `TwingateResource` CRD: `kubectl get tgr my-service-resource -o yaml`. You should see that `alias` is applied on the `spec` object
```yaml
spec:
  name: my-service-resource
  alias: myapp.internal
```
4. Remove `resource.twingate.com/alias` annotation in `service.yaml` and update the Service: `kubectl apply -f service.yaml`
5. Get the `TwingateResource` CRD again: `kubectl get tgr my-service-resource -o yaml`. The `alias` is still there and not removed.
```yaml
spec:
  name: my-service-resource
  alias: myapp.internal
```

**Anything else we need to know?**:
A similar behavior is observed for `metadata.labels` as well, where we can't remove a label on `TwingateResource` CRD once we added it on the k8s Service
