### ISSUE TITLE
When upgrading from 0.21.X -> 0.22.X pods deleted, but deployment not created until the TwingateConnector resource is updated

### ISSUE THREAD

**Issue by rlafferty** [Twingate/kubernetes-operator#673]
**What happened?**

When updating from version `0.21.2` of the twingate-operator to `0.22.1`, the operator came up and correctly deleted the pre-deployment _Pods_ (as expected) killing all connectors in the cluster.  However, new _Deployments_ were **not** created until we manually edited the _TwingateConnector_ resources (or created new ones).

I believe this is due to this method [`twingate_connector_resume`](https://github.com/Twingate/kubernetes-operator/blob/main/app/handlers/handlers_connectors.py#L214-L219) deleting the pre-deployment pods (as it should), but creating and updating deployments only occur on the Create or Update actions on a _TwingateResource_ instance.

**Did you expect to see something different?**
My expectation is the swap from pre-deployment _Pod_ to new _Deployment_ would happen behind the scenes without requiring "updating" existing _TwingateConnector_ resources.

**How to reproduce it (as minimally and precisely as possible)**:

Have a deployment of `0.21.2` twingate-operator running.

Create a connector:
```
apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  labels:
    app.kubernetes.io/name: twingate-connector
  name: twingate-connector-01
spec:
  hasStatusNotificationsEnabled: true
  imagePolicy:
    allowPrerelease: false
    provider: dockerhub
    repository: twingate/connector
    schedule: 0 4 * * *
  logLevel: 6
  podExtra:
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: twingate-connector
      maxSkew: 1
      minDomains: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
```

Update to `0.22.0` on the twingate-operator.

Notice: the pods will disappear (as expected) when the new version of the operator is ready, but the deployment will **NOT** appear.

Update (via `kubectl edit...` the `logLevel` in the TwingateConnector above to `5`, save exit.

Notice: The deployment will appear.

**Environment**

N/A

* Twingate Kubernetes Operator version: `0.22.1` from `0.21.2`

    `Insert image tag or Git SHA here`
    

* Kubernetes version information: `v1.32.3-eks-bcf3d70`

    `kubectl version`
    

* Kubernetes cluster kind: EKS

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Twingate Kubernetes Operator Logs:

```
insert Twingate Kubernetes Operator logs relevant to the issue here
```

**Anything else we need to know?**:
While its certainly not super impactful to update the _TwingateConnector_ resources in a cluster after the new operator version is running, there is a temporary breakage in access to that cluster as the connectors are "gone".
